version: '3.8'

services:
  database-mysql-ia:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: batata
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
